alias "cd.."="cd ../"
alias "cd../"="cd ../"
alias "¿"="locate"
alias -g "..."="../.."
alias -g "...."="../../.."
alias -g "..../"="../../../"
alias -g ".../"="../../"
alias -g egp="| egrep"
alias -g gp="| grep"
alias -g gpi="| grep -i"
alias -g §="| while read line; do; "
alias -g ç="; done"
alias -s csv=vim
alias -s go=vim
alias -s lua=vim
alias -s tex=vim
alias -s txt=vim
alias aj="autojump"
alias alert='notify-send'
alias ca="/bin/cat"
alias cd="pushd"
alias cp="cp -avurf"
alias ct="/bin/cat"
alias deflate="inflate -d -l 9"
alias dropbox="dropbox-cli"
alias e="vim -p"
alias egrep='grep -E --color=auto'
alias ehco="echo"
alias fgrep='grep -nR --color=auto'
alias fuck='sudo !!'
alias fucking="sudo"
alias gdb="gdb -quiet"
alias grep='grep --color=auto'
alias host2ip="dig +short"
alias http="http --pretty all"
alias js="node"
alias kbd_brightness="sudo tee /sys/devices/platform/asus-nb-wmi/leds/asus::kbd_backlight/brightness <<< "
alias ks=ls
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias mv="mv -v"
alias nmap-host-discovery="sudo nmap -sn -vv -n -oA discovery"
alias nmap-list-hosts="nmap -sL -n -PN"
alias nmap-list-script="ls /usr/share/nmap/scripts"
alias nmap-port-scan="sudo nmap -p- -A -Pn -vv -oA portscan"
alias nmap-ssh="nmap --script ssh2-enum-algos -vv -p 22 -Pn -oA nmap-ssh" #TODO filter for hmac 96 bit o md5 o cbc
alias nmap-ssl="nmap -sV -sC -vv -oA nmap-ssl"
alias nmap="sudo nmap"
alias office-to-pdf="libreoffice --headless --invisible --convert-to pdf"
alias sslscan="sslscan --no-failed"
alias stopx="pkill -15 X"
alias swap-flush="sudo swapoff -a && sudo swapon -a"
alias syn-ping="nmap -sn -PS -vv"
alias touch=":>" #Smile!
alias vi="vim -u NONE"
alias vim="vim -p"
alias vimconfig="vim $HOME/.vimrc"
alias vimo="vim -p -M"
alias webshare='python -m http.server'
alias xpath="xmllint --xpath"
alias zshconfig="vim \"$(dirname $0)\"/zshrc-$(hostname).sh && exec zsh"
alias epoch="date +%s"
